import {
  collection,
  getDocs,
  doc,
  writeBatch,
  setDoc,
  getDoc,
} from 'firebase/firestore';
import { db } from './config';
import { Country, Product, PricingRule, Shipment, BlogPost, WebsiteSettings } from '../types';

export const INITIAL_COUNTRIES: Country[] = [
  {
    id: 'c-my',
    name: 'Malaysia',
    code: 'MY',
    flag: '🇲🇾',
    currency: 'MYR',
    basePrice: 1400,
    additionalKgPrice: 600,
    estimatedDays: '3-5 Business Days',
    availableProductIds: ['p-doc', 'p-cloth', 'p-gift', 'p-food', 'p-pers'],
    status: 'active',
    isPopular: true,
    notes: 'Direct cargo flights from Dhaka to KLIA daily. No customs duty on personal gifts up to MYR 500.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c-sa',
    name: 'Saudi Arabia',
    code: 'SA',
    flag: '🇸🇦',
    currency: 'SAR',
    basePrice: 1600,
    additionalKgPrice: 700,
    estimatedDays: '4-6 Business Days',
    availableProductIds: ['p-doc', 'p-cloth', 'p-elec', 'p-food', 'p-pers'],
    status: 'active',
    isPopular: true,
    notes: 'Door-to-door delivery across Riyadh, Jeddah, Dammam & Mecca. Arabic invoice required.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c-ae',
    name: 'United Arab Emirates',
    code: 'AE',
    flag: '🇦🇪',
    currency: 'AED',
    basePrice: 1500,
    additionalKgPrice: 650,
    estimatedDays: '3-4 Business Days',
    availableProductIds: ['p-doc', 'p-cloth', 'p-elec', 'p-gift', 'p-cosm', 'p-food'],
    status: 'active',
    isPopular: true,
    notes: 'Dubai, Sharjah & Abu Dhabi express priority lane. Swift customs clearance.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c-qa',
    name: 'Qatar',
    code: 'QA',
    flag: '🇶🇦',
    currency: 'QAR',
    basePrice: 1600,
    additionalKgPrice: 700,
    estimatedDays: '3-5 Business Days',
    availableProductIds: ['p-doc', 'p-cloth', 'p-gift', 'p-food', 'p-pers'],
    status: 'active',
    isPopular: true,
    notes: 'Doha express delivery with SMS verification upon delivery.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c-om',
    name: 'Oman',
    code: 'OM',
    flag: '🇴🇲',
    currency: 'OMR',
    basePrice: 1550,
    additionalKgPrice: 680,
    estimatedDays: '4-6 Business Days',
    availableProductIds: ['p-doc', 'p-cloth', 'p-food', 'p-pers'],
    status: 'active',
    isPopular: true,
    notes: 'Muscat and Salalah delivery network.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c-gb',
    name: 'United Kingdom',
    code: 'GB',
    flag: '🇬🇧',
    currency: 'GBP',
    basePrice: 2200,
    additionalKgPrice: 850,
    estimatedDays: '3-5 Business Days',
    availableProductIds: ['p-doc', 'p-cloth', 'p-elec', 'p-gift', 'p-comm', 'p-pers'],
    status: 'active',
    isPopular: true,
    notes: 'Priority air courier via London Heathrow. UK VAT and customs paperwork managed.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c-us',
    name: 'United States',
    code: 'US',
    flag: '🇺🇸',
    currency: 'USD',
    basePrice: 2400,
    additionalKgPrice: 950,
    estimatedDays: '4-6 Business Days',
    availableProductIds: ['p-doc', 'p-cloth', 'p-gift', 'p-comm', 'p-pers'],
    status: 'active',
    isPopular: true,
    notes: 'Full coverage all 50 states via JFK, OHARE & LAX gateways. Strict FDA rules on food.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c-ca',
    name: 'Canada',
    code: 'CA',
    flag: '🇨🇦',
    currency: 'CAD',
    basePrice: 2500,
    additionalKgPrice: 1000,
    estimatedDays: '4-7 Business Days',
    availableProductIds: ['p-doc', 'p-cloth', 'p-gift', 'p-comm', 'p-pers'],
    status: 'active',
    isPopular: true,
    notes: 'Toronto, Montreal, Vancouver & Calgary express hubs.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c-au',
    name: 'Australia',
    code: 'AU',
    flag: '🇦🇺',
    currency: 'AUD',
    basePrice: 2600,
    additionalKgPrice: 1050,
    estimatedDays: '4-7 Business Days',
    availableProductIds: ['p-doc', 'p-cloth', 'p-gift', 'p-comm', 'p-pers'],
    status: 'active',
    isPopular: true,
    notes: 'Sydney, Melbourne & Brisbane courier corridor. Strict biosecurity declaration required.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c-sg',
    name: 'Singapore',
    code: 'SG',
    flag: '🇸🇬',
    currency: 'SGD',
    basePrice: 1350,
    additionalKgPrice: 580,
    estimatedDays: '2-4 Business Days',
    availableProductIds: ['p-doc', 'p-cloth', 'p-elec', 'p-gift', 'p-comm', 'p-food'],
    status: 'active',
    isPopular: true,
    notes: 'Fastest transit lane from Dhaka. Express same-day clearing at Changi.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c-it',
    name: 'Italy',
    code: 'IT',
    flag: '🇮🇹',
    currency: 'EUR',
    basePrice: 2300,
    additionalKgPrice: 900,
    estimatedDays: '4-6 Business Days',
    availableProductIds: ['p-doc', 'p-cloth', 'p-gift', 'p-pers'],
    status: 'active',
    isPopular: true,
    notes: 'Rome and Milan hubs with fast dispatch to Bologna, Venice, and Naples.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c-in',
    name: 'India',
    code: 'IN',
    flag: '🇮🇳',
    currency: 'INR',
    basePrice: 1100,
    additionalKgPrice: 450,
    estimatedDays: '2-4 Business Days',
    availableProductIds: ['p-doc', 'p-cloth', 'p-gift', 'p-comm'],
    status: 'active',
    isPopular: false,
    notes: 'Kolkata, Delhi & Mumbai connections. KYC verification required for consignee.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'p-doc',
    name: 'Documents',
    code: 'DOC',
    category: 'Paper & Files',
    description: 'Passports, legal contracts, certificates, university admission files, bank documents.',
    icon: 'FileText',
    status: 'active',
    maxWeight: 5,
    restricted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p-cloth',
    name: 'Clothes & Apparel',
    code: 'CLOTH',
    category: 'Garments',
    description: 'Sharee, Panjabi, cotton dresses, winter jackets, stitched clothes, textiles.',
    icon: 'Shirt',
    status: 'active',
    maxWeight: 50,
    restricted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p-elec',
    name: 'Electronics',
    code: 'ELEC',
    category: 'Technology',
    description: 'Gadgets, phones, circuit components, smart watches (requires IATA battery declaration).',
    icon: 'Laptop',
    status: 'active',
    maxWeight: 15,
    restricted: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p-gift',
    name: 'Gifts & Hampers',
    code: 'GIFT',
    category: 'Presents',
    description: 'Bangladeshi handicrafts, souvenirs, wedding gifts, jewelry boxes, personalized items.',
    icon: 'Gift',
    status: 'active',
    maxWeight: 20,
    restricted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p-food',
    name: 'Dry Food & Snacks',
    code: 'FOOD',
    category: 'Foodstuff',
    description: 'Dry sweets, biscuits, spices, tea packets, sealed dry bakery items (must be vacuum-packed).',
    icon: 'Utensils',
    status: 'active',
    maxWeight: 10,
    restricted: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p-cosm',
    name: 'Cosmetics',
    code: 'COSM',
    category: 'Personal Care',
    description: 'Non-liquid cosmetics, herbal powders, beauty kits, skincare creams.',
    icon: 'Sparkles',
    status: 'active',
    maxWeight: 10,
    restricted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p-pers',
    name: 'Personal Belongings',
    code: 'PERS',
    category: 'General',
    description: 'Used books, shoes, bags, home utility items for expatriates and students.',
    icon: 'Package',
    status: 'active',
    maxWeight: 60,
    restricted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p-comm',
    name: 'Commercial Goods',
    code: 'COMM',
    category: 'Business Consignments',
    description: 'Export swatches, garment factory samples, machinery parts, trade samples.',
    icon: 'Briefcase',
    status: 'active',
    maxWeight: 150,
    restricted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_PRICING_RULES: PricingRule[] = [
  // Malaysia
  {
    id: 'pr-my-doc',
    countryId: 'c-my',
    countryName: 'Malaysia',
    productId: 'p-doc',
    productName: 'Documents',
    pricingType: 'base_plus_additional',
    baseKg: 1,
    basePrice: 1400,
    additionalKgPrice: 600,
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pr-my-cloth',
    countryId: 'c-my',
    countryName: 'Malaysia',
    productId: 'p-cloth',
    productName: 'Clothes & Apparel',
    pricingType: 'slabs',
    slabs: [
      { minKg: 0, maxKg: 1, price: 1600 },
      { minKg: 1, maxKg: 2, price: 2200 },
      { minKg: 2, maxKg: 3, price: 2800 },
      { minKg: 3, maxKg: 5, price: 3900 },
      { minKg: 5, maxKg: 10, price: 6800 },
    ],
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pr-my-gift',
    countryId: 'c-my',
    countryName: 'Malaysia',
    productId: 'p-gift',
    productName: 'Gifts & Hampers',
    pricingType: 'base_plus_additional',
    baseKg: 1,
    basePrice: 1700,
    additionalKgPrice: 650,
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Saudi Arabia
  {
    id: 'pr-sa-doc',
    countryId: 'c-sa',
    countryName: 'Saudi Arabia',
    productId: 'p-doc',
    productName: 'Documents',
    pricingType: 'base_plus_additional',
    baseKg: 1,
    basePrice: 1600,
    additionalKgPrice: 700,
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pr-sa-cloth',
    countryId: 'c-sa',
    countryName: 'Saudi Arabia',
    productId: 'p-cloth',
    productName: 'Clothes & Apparel',
    pricingType: 'slabs',
    slabs: [
      { minKg: 0, maxKg: 1, price: 1800 },
      { minKg: 1, maxKg: 2, price: 2500 },
      { minKg: 2, maxKg: 3, price: 3200 },
      { minKg: 3, maxKg: 5, price: 4600 },
      { minKg: 5, maxKg: 10, price: 7900 },
    ],
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // UAE
  {
    id: 'pr-ae-doc',
    countryId: 'c-ae',
    countryName: 'United Arab Emirates',
    productId: 'p-doc',
    productName: 'Documents',
    pricingType: 'base_plus_additional',
    baseKg: 1,
    basePrice: 1500,
    additionalKgPrice: 650,
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pr-ae-cloth',
    countryId: 'c-ae',
    countryName: 'United Arab Emirates',
    productId: 'p-cloth',
    productName: 'Clothes & Apparel',
    pricingType: 'base_plus_additional',
    baseKg: 1,
    basePrice: 1700,
    additionalKgPrice: 720,
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // UK
  {
    id: 'pr-gb-doc',
    countryId: 'c-gb',
    countryName: 'United Kingdom',
    productId: 'p-doc',
    productName: 'Documents',
    pricingType: 'base_plus_additional',
    baseKg: 1,
    basePrice: 2200,
    additionalKgPrice: 850,
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pr-gb-cloth',
    countryId: 'c-gb',
    countryName: 'United Kingdom',
    productId: 'p-cloth',
    productName: 'Clothes & Apparel',
    pricingType: 'slabs',
    slabs: [
      { minKg: 0, maxKg: 1, price: 2400 },
      { minKg: 1, maxKg: 2, price: 3250 },
      { minKg: 2, maxKg: 3, price: 4100 },
      { minKg: 3, maxKg: 5, price: 5800 },
      { minKg: 5, maxKg: 10, price: 9900 },
    ],
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // USA
  {
    id: 'pr-us-doc',
    countryId: 'c-us',
    countryName: 'United States',
    productId: 'p-doc',
    productName: 'Documents',
    pricingType: 'base_plus_additional',
    baseKg: 1,
    basePrice: 2400,
    additionalKgPrice: 950,
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Canada
  {
    id: 'pr-ca-doc',
    countryId: 'c-ca',
    countryName: 'Canada',
    productId: 'p-doc',
    productName: 'Documents',
    pricingType: 'base_plus_additional',
    baseKg: 1,
    basePrice: 2500,
    additionalKgPrice: 1000,
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pr-ca-cloth',
    countryId: 'c-ca',
    countryName: 'Canada',
    productId: 'p-cloth',
    productName: 'Clothes & Apparel',
    pricingType: 'base_plus_additional',
    baseKg: 1,
    basePrice: 2700,
    additionalKgPrice: 1100,
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Australia
  {
    id: 'pr-au-doc',
    countryId: 'c-au',
    countryName: 'Australia',
    productId: 'p-doc',
    productName: 'Documents',
    pricingType: 'base_plus_additional',
    baseKg: 1,
    basePrice: 2600,
    additionalKgPrice: 1050,
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pr-au-cloth',
    countryId: 'c-au',
    countryName: 'Australia',
    productId: 'p-cloth',
    productName: 'Clothes & Apparel',
    pricingType: 'slabs',
    slabs: [
      { minKg: 0, maxKg: 1, price: 2800 },
      { minKg: 1, maxKg: 2, price: 3850 },
      { minKg: 2, maxKg: 3, price: 4900 },
      { minKg: 3, maxKg: 5, price: 6900 },
    ],
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Singapore
  {
    id: 'pr-sg-doc',
    countryId: 'c-sg',
    countryName: 'Singapore',
    productId: 'p-doc',
    productName: 'Documents',
    pricingType: 'base_plus_additional',
    baseKg: 1,
    basePrice: 1350,
    additionalKgPrice: 580,
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pr-sg-cloth',
    countryId: 'c-sg',
    countryName: 'Singapore',
    productId: 'p-cloth',
    productName: 'Clothes & Apparel',
    pricingType: 'base_plus_additional',
    baseKg: 1,
    basePrice: 1550,
    additionalKgPrice: 620,
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Qatar
  {
    id: 'pr-qa-doc',
    countryId: 'c-qa',
    countryName: 'Qatar',
    productId: 'p-doc',
    productName: 'Documents',
    pricingType: 'base_plus_additional',
    baseKg: 1,
    basePrice: 1600,
    additionalKgPrice: 700,
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pr-qa-cloth',
    countryId: 'c-qa',
    countryName: 'Qatar',
    productId: 'p-cloth',
    productName: 'Clothes & Apparel',
    pricingType: 'base_plus_additional',
    baseKg: 1,
    basePrice: 1750,
    additionalKgPrice: 750,
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Oman
  {
    id: 'pr-om-doc',
    countryId: 'c-om',
    countryName: 'Oman',
    productId: 'p-doc',
    productName: 'Documents',
    pricingType: 'base_plus_additional',
    baseKg: 1,
    basePrice: 1550,
    additionalKgPrice: 680,
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Italy
  {
    id: 'pr-it-doc',
    countryId: 'c-it',
    countryName: 'Italy',
    productId: 'p-doc',
    productName: 'Documents',
    pricingType: 'base_plus_additional',
    baseKg: 1,
    basePrice: 2300,
    additionalKgPrice: 900,
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // India
  {
    id: 'pr-in-doc',
    countryId: 'c-in',
    countryName: 'India',
    productId: 'p-doc',
    productName: 'Documents',
    pricingType: 'base_plus_additional',
    baseKg: 1,
    basePrice: 1100,
    additionalKgPrice: 450,
    status: 'active',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_SHIPMENTS: Shipment[] = [
  {
    id: 'ship-101',
    trackingNumber: 'YP8840291BD',
    senderName: 'Kabir Hossain',
    senderPhone: '+8801712345678',
    senderEmail: 'kabir.hossain@gmail.com',
    senderAddress: 'House 42, Road 9/A, Dhanmondi',
    senderCity: 'Dhaka',
    receiverName: 'Farhan Rahman',
    receiverPhone: '+60129876543',
    receiverEmail: 'farhan.r@klgroup.my',
    receiverAddress: 'No. 18, Jalan Bukit Bintang, 55100',
    destinationCountry: 'Malaysia',
    destinationCountryCode: 'MY',
    productId: 'p-cloth',
    productName: 'Clothes & Apparel',
    weight: 3.5,
    quantity: 1,
    dimensions: '35 x 25 x 15 cm',
    totalPrice: 3900,
    currency: 'BDT',
    paymentStatus: 'paid',
    paymentMethod: 'bKash Merchant Pay',
    status: 'in_transit',
    currentLocation: 'Kuala Lumpur International Airport (KLIA Cargo Hub)',
    estimatedDelivery: 'Oct 09, 2026',
    events: [
      {
        id: 'ev-1',
        status: 'order_received',
        title: 'Booking Confirmed & Waybill Generated',
        location: 'Dhaka Central Hub, Bangladesh',
        note: 'Consignment booked online. Dispatch unit assigned.',
        timestamp: '2026-10-04 10:15 AM',
      },
      {
        id: 'ev-2',
        status: 'picked_up',
        title: 'Parcel Picked Up from Shipper',
        location: 'Dhanmondi, Dhaka',
        note: 'Courier agent collected package and verified security seals.',
        timestamp: '2026-10-04 03:30 PM',
      },
      {
        id: 'ev-3',
        status: 'processing',
        title: 'Customs Clearance & Air Cargo Manifested',
        location: 'Hazrat Shahjalal International Airport (DAC)',
        note: 'Passed export scanner and loaded into Malaysian Airlines MH197 cargo bay.',
        timestamp: '2026-10-05 09:40 PM',
      },
      {
        id: 'ev-4',
        status: 'in_transit',
        title: 'Flight Arrived at Transit Hub',
        location: 'KLIA Cargo Terminal, Malaysia',
        note: 'Undergoing inbound customs inspection at Sepang.',
        timestamp: '2026-10-06 08:20 AM',
      },
    ],
    createdAt: '2026-10-04T04:15:00.000Z',
    updatedAt: '2026-10-06T02:20:00.000Z',
  },
  {
    id: 'ship-102',
    trackingNumber: 'YP9918234BD',
    senderName: 'Nadia Islam',
    senderPhone: '+8801819234567',
    senderEmail: 'nadia.islam@gmail.com',
    senderAddress: '24 Agrabad Commercial Area',
    senderCity: 'Chittagong',
    receiverName: 'Tariqul Islam',
    receiverPhone: '+447911123456',
    receiverEmail: 'tariqul.i@london.ac.uk',
    receiverAddress: 'Flat 4B, 82 Whitechapel High St, London E1 7QX',
    destinationCountry: 'United Kingdom',
    destinationCountryCode: 'GB',
    productId: 'p-doc',
    productName: 'Documents',
    weight: 0.8,
    quantity: 1,
    dimensions: '30 x 22 x 2 cm',
    totalPrice: 2200,
    currency: 'BDT',
    paymentStatus: 'paid',
    paymentMethod: 'Bank Transfer (City Bank)',
    status: 'out_for_delivery',
    currentLocation: 'Royal Mail Central London Delivery Office',
    estimatedDelivery: 'Oct 07, 2026 (Today)',
    events: [
      {
        id: 'ev-11',
        status: 'order_received',
        title: 'Booking Created',
        location: 'Chittagong Branch, Bangladesh',
        timestamp: '2026-10-03 11:00 AM',
      },
      {
        id: 'ev-12',
        status: 'picked_up',
        title: 'Picked Up by Chittagong Courier',
        location: 'Agrabad, Chittagong',
        timestamp: '2026-10-03 02:45 PM',
      },
      {
        id: 'ev-13',
        status: 'processing',
        title: 'Dispatched via Express Flight from Dhaka Hub',
        location: 'Hazrat Shahjalal Int Airport (DAC)',
        timestamp: '2026-10-04 07:15 PM',
      },
      {
        id: 'ev-14',
        status: 'arrived_destination',
        title: 'Cleared UK Customs at London Heathrow (LHR)',
        location: 'London Heathrow Gateway',
        timestamp: '2026-10-05 06:10 PM',
      },
      {
        id: 'ev-15',
        status: 'out_for_delivery',
        title: 'With Delivery Courier for Final Drop-off',
        location: 'Whitechapel, London',
        note: 'Courier van en route to consignee address.',
        timestamp: '2026-10-07 08:30 AM',
      },
    ],
    createdAt: '2026-10-03T05:00:00.000Z',
    updatedAt: '2026-10-07T02:30:00.000Z',
  },
  {
    id: 'ship-103',
    trackingNumber: 'YP7721540BD',
    senderName: 'Mahmudur Rahman',
    senderPhone: '+8801912987654',
    senderEmail: 'mahmud.rahman@outlook.com',
    senderAddress: 'Plot 15, Road 4, Sector 7, Uttara',
    senderCity: 'Dhaka',
    receiverName: 'Saad Al-Mansoor',
    receiverPhone: '+966551234567',
    receiverEmail: 'saad.mansoor@alriyadh.com',
    receiverAddress: 'Olaya District, King Fahd Rd, Riyadh 12211',
    destinationCountry: 'Saudi Arabia',
    destinationCountryCode: 'SA',
    productId: 'p-cloth',
    productName: 'Clothes & Apparel',
    weight: 2.5,
    quantity: 1,
    dimensions: '30 x 25 x 12 cm',
    totalPrice: 3200,
    currency: 'BDT',
    paymentStatus: 'paid',
    paymentMethod: 'Nagad Online',
    status: 'delivered',
    currentLocation: 'Delivered - Riyadh, Saudi Arabia',
    estimatedDelivery: 'Oct 05, 2026',
    events: [
      {
        id: 'ev-21',
        status: 'order_received',
        title: 'Shipment Processed',
        location: 'Uttara Hub, Dhaka',
        timestamp: '2026-09-30 09:00 AM',
      },
      {
        id: 'ev-22',
        status: 'picked_up',
        title: 'Parcel Received at Export Terminal',
        location: 'Dhaka Airport Hub',
        timestamp: '2026-09-30 04:00 PM',
      },
      {
        id: 'ev-23',
        status: 'in_transit',
        title: 'Flown to King Khalid Int Airport (RUH)',
        location: 'Riyadh, Saudi Arabia',
        timestamp: '2026-10-02 01:20 PM',
      },
      {
        id: 'ev-24',
        status: 'out_for_delivery',
        title: 'Dispatched for Doorstep Handover',
        location: 'Olaya, Riyadh',
        timestamp: '2026-10-05 10:15 AM',
      },
      {
        id: 'ev-25',
        status: 'delivered',
        title: 'Successfully Delivered & Signed by Receiver',
        location: 'Riyadh, Saudi Arabia',
        note: 'Signed by: S. Mansoor. Verified via delivery pin.',
        timestamp: '2026-10-05 02:40 PM',
      },
    ],
    createdAt: '2026-09-30T03:00:00.000Z',
    updatedAt: '2026-10-05T08:40:00.000Z',
  },
];

export const INITIAL_BLOG_POSTS: BlogPost[] = [
  {
    id: 'post-1',
    title: 'Essential Guide to Sending Documents from Bangladesh to the UK & Europe',
    slug: 'guide-sending-documents-bangladesh-to-uk-europe',
    featuredImage: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=1200&q=80',
    description: 'Everything you need to know about preparing university certificates, legal papers, and passports for fast international courier delivery.',
    content: `When sending critical legal documents, higher education credentials, or employment contracts from Bangladesh to the UK or Europe, speed and security are paramount. 

At YOUR PARCEL, all document shipments are sealed in tamper-evident waterproof pouches with specialized barcode serialization.

### 1. Verification of Paperwork
Ensure your copies are clearly arranged in order. For academic credentials being dispatched to WES (World Education Services) or British universities, enclose them in an official institutional envelope with the registrar seal before handing to our courier.

### 2. Prohibited Inclusions in Document Pouches
Currency notes, bank cards with active chips, or electronic storage keys cannot be sent as standard document mail and require declaration as personal valuables.

### 3. Real-Time Tracking
All documents travel on priority express flights with dedicated ground expeditors in London Heathrow, Frankfurt, and Rome, delivering within 3-5 business days.`,
    category: 'Guides',
    author: 'YOUR PARCEL Logistics Team',
    status: 'published',
    seoTitle: 'Send Documents from Bangladesh to UK - YOUR PARCEL Guide',
    seoDescription: 'Fast & secure document courier service from Dhaka to the UK and Europe. 3-5 days delivery guarantee.',
    keywords: 'courier documents bangladesh uk, express parcel dhaka london, certificate shipping',
    publishedAt: '2026-10-01T08:00:00.000Z',
    createdAt: '2026-10-01T08:00:00.000Z',
    updatedAt: '2026-10-01T08:00:00.000Z',
  },
  {
    id: 'post-2',
    title: 'Customs Rules for Clothes and Traditional Attire to Malaysia & Middle East',
    slug: 'customs-rules-clothes-malaysia-middle-east',
    featuredImage: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=1200&q=80',
    description: 'How to ship Jamdani sharees, Eid attire, Panjabis, and gift clothes smoothly to family living in Malaysia, Saudi Arabia, and UAE.',
    content: `Sending clothes to relatives residing in Malaysia, Saudi Arabia, UAE, and Qatar is one of the most frequent services requested by Bangladeshi expatriates.

### Declaring Value for Personal Gifts
Both Malaysian Customs (Royal Malaysian Customs Department) and ZATCA (Saudi Zakat, Tax and Customs Authority) allow personal gifts under designated threshold limits without commercial duty.

### Packaging Best Practices
1. Wrap each Jamdani or silk sharee individually in acid-free tissue or polyethylene wrap.
2. Avoid sending wet or unwashed fabrics.
3. Keep tags removed or clearly marked as "Personal Family Gift - Not for Resale".

YOUR PARCEL provides complimentary moisture-resistant outer carton boxes at our Dhaka, Chittagong, and Sylhet booking offices.`,
    category: 'Customs Tips',
    author: 'Global Customs Desk',
    status: 'published',
    seoTitle: 'Shipping Clothes to Malaysia & Middle East from Bangladesh',
    seoDescription: 'Complete customs guide for sending clothes, sharees and gifts from Bangladesh abroad.',
    keywords: 'courier clothes bangladesh, ship sharee to malaysia, courier to saudi arabia',
    publishedAt: '2026-10-03T10:00:00.000Z',
    createdAt: '2026-10-03T10:00:00.000Z',
    updatedAt: '2026-10-03T10:00:00.000Z',
  },
  {
    id: 'post-3',
    title: 'How Volumetric Weight Works in International Air Cargo Shipping',
    slug: 'how-volumetric-weight-works-international-air-cargo',
    featuredImage: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80',
    description: 'Learn how international airlines calculate billable weight using the dimensional formula: (L x W x H) / 5000.',
    content: `Have you ever wondered why shipping a large box of lightweight foam or jackets costs more than shipping a small dense packet of heavy books?

In aviation logistics, airplanes have both weight limits and cubic volume constraints. Therefore, the International Air Transport Association (IATA) standardizes **Volumetric (Dimensional) Weight**.

### The Universal Air Freight Formula
**Volumetric Weight (KG) = (Length cm × Width cm × Height cm) ÷ 5000**

The chargeable weight is always whichever is higher: the actual scale weight or the volumetric weight.

### Our Pro-Tip: Compression Packing
When you send winter clothing, soft toys, or textiles, request vacuum-sealed packing at any YOUR PARCEL branch to reduce carton dimensions and save up to 40% on shipping charges!`,
    category: 'Logistics 101',
    author: 'Air Cargo Operations',
    status: 'published',
    seoTitle: 'Understanding Volumetric Weight - YOUR PARCEL Logistics',
    seoDescription: 'Calculate dimensional weight for air courier parcels from Bangladesh with our easy guide.',
    keywords: 'volumetric weight calculator, air freight courier weight, international parcel dimensions',
    publishedAt: '2026-10-05T09:30:00.000Z',
    createdAt: '2026-10-05T09:30:00.000Z',
    updatedAt: '2026-10-05T09:30:00.000Z',
  },
];

export const INITIAL_WEBSITE_SETTINGS: WebsiteSettings = {
  brandName: 'YOUR PARCEL',
  tagline: 'Your parcel, our responsibility.',
  heroTitle: 'Your parcel, our responsibility.',
  heroSubtitle: 'Fast, secure and trackable international courier service from Bangladesh to destinations around the world.',
  phone: '+880 1819-000000',
  hotline: '16999',
  email: 'support@yourparcel.com.bd',
  address: 'Level 5, Navana Tower, Gulshan-1, Dhaka-1212, Bangladesh',
  whatsappNumber: '+8801819000000',
  facebookUrl: 'https://facebook.com/yourparcelbd',
  instagramUrl: 'https://instagram.com/yourparcelbd',
  linkedinUrl: 'https://linkedin.com/company/yourparcel',
  noticeBanner: '✈️ Special Daily Cargo Flights now active from Dhaka to Malaysia, UAE, Saudi Arabia & UK with Express Priority Handling!',
  noticeBannerActive: true,
  currencySymbol: '৳',
  logoUrl: '',
  logoType: 'default',
};

export async function seedInitialDataIfEmpty(): Promise<boolean> {
  try {
    const countriesSnapshot = await getDocs(collection(db, 'countries'));
    if (!countriesSnapshot.empty) {
      console.log('Database already initialized with data.');
      return false;
    }

    console.log('Seeding initial YOUR PARCEL data into Firestore...');
    const batch = writeBatch(db);

    // Countries
    for (const country of INITIAL_COUNTRIES) {
      batch.set(doc(db, 'countries', country.id), country);
    }

    // Products
    for (const product of INITIAL_PRODUCTS) {
      batch.set(doc(db, 'products', product.id), product);
    }

    // Pricing Rules
    for (const rule of INITIAL_PRICING_RULES) {
      batch.set(doc(db, 'pricingRules', rule.id), rule);
    }

    // Demo Shipments
    for (const shipment of INITIAL_SHIPMENTS) {
      batch.set(doc(db, 'shipments', shipment.id), shipment);
    }

    // Blog Posts
    for (const post of INITIAL_BLOG_POSTS) {
      batch.set(doc(db, 'blogPosts', post.id), post);
    }

    // Website CMS settings
    batch.set(doc(db, 'websiteSettings', 'general'), INITIAL_WEBSITE_SETTINGS);

    // Initial notification for admin
    batch.set(doc(db, 'notifications', 'notif-welcome'), {
      id: 'notif-welcome',
      title: 'Welcome to YOUR PARCEL Admin Dashboard',
      message: 'System initialized. Pricing engine, tracking system, and live Firebase synchronization are operational.',
      type: 'system',
      read: false,
      link: '/admin',
      createdAt: new Date().toISOString(),
    });

    // Initial activity log
    batch.set(doc(db, 'activityLogs', 'log-init'), {
      id: 'log-init',
      adminEmail: 'gazisohan37@gmail.com',
      action: 'System Initialized',
      details: 'Populated 12 destination countries, 8 parcel categories, and country-specific dynamic pricing rules.',
      category: 'system',
      timestamp: new Date().toISOString(),
    });

    await batch.commit();
    console.log('Firestore seed complete!');
    return true;
  } catch (error) {
    console.warn('Seeding check note:', error);
    return false;
  }
}
